# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyEnvDAQGUI.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PyEnvDAQ(object):
    def setupUi(self, PyEnvDAQ):
        PyEnvDAQ.setObjectName("PyEnvDAQ")
        PyEnvDAQ.resize(957, 1034)
        self.centralWidget = QtWidgets.QWidget(PyEnvDAQ)
        self.centralWidget.setObjectName("centralWidget")
        self.pushButtonStart = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonStart.setGeometry(QtCore.QRect(770, 10, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.pushButtonStart.setFont(font)
        self.pushButtonStart.setCheckable(True)
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.buttonGroup_5 = QtWidgets.QButtonGroup(PyEnvDAQ)
        self.buttonGroup_5.setObjectName("buttonGroup_5")
        self.buttonGroup_5.addButton(self.pushButtonStart)
        self.labelProgramName = QtWidgets.QLabel(self.centralWidget)
        self.labelProgramName.setGeometry(QtCore.QRect(20, 0, 161, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelProgramName.sizePolicy().hasHeightForWidth())
        self.labelProgramName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(24)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.labelProgramName.setFont(font)
        self.labelProgramName.setTextFormat(QtCore.Qt.PlainText)
        self.labelProgramName.setAlignment(QtCore.Qt.AlignCenter)
        self.labelProgramName.setObjectName("labelProgramName")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(60, 63, 201, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setObjectName("label_2")
        self.labelDataWillBeSavedInto = QtWidgets.QLabel(self.centralWidget)
        self.labelDataWillBeSavedInto.setGeometry(QtCore.QRect(30, 48, 711, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDataWillBeSavedInto.sizePolicy().hasHeightForWidth())
        self.labelDataWillBeSavedInto.setSizePolicy(sizePolicy)
        self.labelDataWillBeSavedInto.setMaximumSize(QtCore.QSize(16777215, 16777214))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        self.labelDataWillBeSavedInto.setFont(font)
        self.labelDataWillBeSavedInto.setTextFormat(QtCore.Qt.PlainText)
        self.labelDataWillBeSavedInto.setObjectName("labelDataWillBeSavedInto")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 120, 921, 871))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tabChannels = QtWidgets.QWidget()
        self.tabChannels.setObjectName("tabChannels")
        self.tableChannels = QtWidgets.QTableWidget(self.tabChannels)
        self.tableChannels.setGeometry(QtCore.QRect(10, 10, 891, 701))
        self.tableChannels.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableChannels.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableChannels.setLineWidth(1)
        self.tableChannels.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableChannels.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableChannels.setObjectName("tableChannels")
        self.tableChannels.setColumnCount(9)
        self.tableChannels.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableChannels.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableChannels.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableChannels.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableChannels.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableChannels.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableChannels.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableChannels.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableChannels.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableChannels.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableChannels.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableChannels.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableChannels.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableChannels.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableChannels.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableChannels.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableChannels.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableChannels.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableChannels.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableChannels.setItem(0, 8, item)
        self.tabWidget.addTab(self.tabChannels, "")
        self.tabActions = QtWidgets.QWidget()
        self.tabActions.setObjectName("tabActions")
        self.comboBoxChannel1 = QtWidgets.QComboBox(self.tabActions)
        self.comboBoxChannel1.setGeometry(QtCore.QRect(220, 155, 211, 31))
        self.comboBoxChannel1.setObjectName("comboBoxChannel1")
        self.comboBoxTimeUnit = QtWidgets.QComboBox(self.tabActions)
        self.comboBoxTimeUnit.setGeometry(QtCore.QRect(510, 20, 101, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        self.comboBoxTimeUnit.setFont(font)
        self.comboBoxTimeUnit.setObjectName("comboBoxTimeUnit")
        self.comboBoxTimeUnit.addItem("")
        self.comboBoxTimeUnit.addItem("")
        self.comboBoxTimeUnit.addItem("")
        self.comboBoxTimeUnit.addItem("")
        self.comboBoxTimeUnit.addItem("")
        self.comboBoxTimeUnit.addItem("")
        self.comboBoxTimeDuration = QtWidgets.QComboBox(self.tabActions)
        self.comboBoxTimeDuration.setGeometry(QtCore.QRect(440, 20, 61, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        self.comboBoxTimeDuration.setFont(font)
        self.comboBoxTimeDuration.setObjectName("comboBoxTimeDuration")
        self.comboBoxTimeDuration.addItem("")
        self.comboBoxTimeDuration.addItem("")
        self.comboBoxTimeDuration.addItem("")
        self.comboBoxTimeDuration.addItem("")
        self.comboBoxTimeDuration.addItem("")
        self.comboBoxTimeDuration.addItem("")
        self.pushButtonExecute = QtWidgets.QPushButton(self.tabActions)
        self.pushButtonExecute.setGeometry(QtCore.QRect(800, 20, 101, 61))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonExecute.setFont(font)
        self.pushButtonExecute.setObjectName("pushButtonExecute")
        self.checkBoxAutoUpdate = QtWidgets.QCheckBox(self.tabActions)
        self.checkBoxAutoUpdate.setGeometry(QtCore.QRect(555, 310, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        self.checkBoxAutoUpdate.setFont(font)
        self.checkBoxAutoUpdate.setObjectName("checkBoxAutoUpdate")
        self.graphicsViewPlot = QtWidgets.QGraphicsView(self.tabActions)
        self.graphicsViewPlot.setGeometry(QtCore.QRect(20, 350, 871, 471))
        self.graphicsViewPlot.setObjectName("graphicsViewPlot")
        self.radioButtonTimePreset = QtWidgets.QRadioButton(self.tabActions)
        self.radioButtonTimePreset.setGeometry(QtCore.QRect(360, 20, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(14)
        self.radioButtonTimePreset.setFont(font)
        self.radioButtonTimePreset.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.radioButtonTimePreset.setChecked(True)
        self.radioButtonTimePreset.setObjectName("radioButtonTimePreset")
        self.buttonGroup_7 = QtWidgets.QButtonGroup(PyEnvDAQ)
        self.buttonGroup_7.setObjectName("buttonGroup_7")
        self.buttonGroup_7.addButton(self.radioButtonTimePreset)
        self.radioButtonTimeSpecific = QtWidgets.QRadioButton(self.tabActions)
        self.radioButtonTimeSpecific.setGeometry(QtCore.QRect(360, 55, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(14)
        self.radioButtonTimeSpecific.setFont(font)
        self.radioButtonTimeSpecific.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.radioButtonTimeSpecific.setChecked(False)
        self.radioButtonTimeSpecific.setObjectName("radioButtonTimeSpecific")
        self.buttonGroup_7.addButton(self.radioButtonTimeSpecific)
        self.radioButtonPlot = QtWidgets.QRadioButton(self.tabActions)
        self.radioButtonPlot.setGeometry(QtCore.QRect(10, 20, 90, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(14)
        self.radioButtonPlot.setFont(font)
        self.radioButtonPlot.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.radioButtonPlot.setChecked(True)
        self.radioButtonPlot.setObjectName("radioButtonPlot")
        self.buttonGroup_6 = QtWidgets.QButtonGroup(PyEnvDAQ)
        self.buttonGroup_6.setObjectName("buttonGroup_6")
        self.buttonGroup_6.addButton(self.radioButtonPlot)
        self.radioButtonExport = QtWidgets.QRadioButton(self.tabActions)
        self.radioButtonExport.setGeometry(QtCore.QRect(90, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(14)
        self.radioButtonExport.setFont(font)
        self.radioButtonExport.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.radioButtonExport.setChecked(False)
        self.radioButtonExport.setObjectName("radioButtonExport")
        self.buttonGroup_6.addButton(self.radioButtonExport)
        self.textEditStartDate = QtWidgets.QTextEdit(self.tabActions)
        self.textEditStartDate.setGeometry(QtCore.QRect(425, 50, 151, 31))
        self.textEditStartDate.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        self.textEditStartDate.setFont(font)
        self.textEditStartDate.setObjectName("textEditStartDate")
        self.textEditEndDate = QtWidgets.QTextEdit(self.tabActions)
        self.textEditEndDate.setGeometry(QtCore.QRect(610, 50, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        self.textEditEndDate.setFont(font)
        self.textEditEndDate.setObjectName("textEditEndDate")
        self.labelTo = QtWidgets.QLabel(self.tabActions)
        self.labelTo.setGeometry(QtCore.QRect(585, 55, 21, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTo.sizePolicy().hasHeightForWidth())
        self.labelTo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        self.labelTo.setFont(font)
        self.labelTo.setTextFormat(QtCore.Qt.PlainText)
        self.labelTo.setObjectName("labelTo")
        self.comboBoxResolution = QtWidgets.QComboBox(self.tabActions)
        self.comboBoxResolution.setGeometry(QtCore.QRect(450, 310, 75, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        self.comboBoxResolution.setFont(font)
        self.comboBoxResolution.setObjectName("comboBoxResolution")
        self.comboBoxResolution.addItem("")
        self.comboBoxResolution.addItem("")
        self.comboBoxResolution.addItem("")
        self.comboBoxResolution.addItem("")
        self.comboBoxResolution.addItem("")
        self.labelResolution = QtWidgets.QLabel(self.tabActions)
        self.labelResolution.setGeometry(QtCore.QRect(350, 310, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelResolution.sizePolicy().hasHeightForWidth())
        self.labelResolution.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        self.labelResolution.setFont(font)
        self.labelResolution.setTextFormat(QtCore.Qt.PlainText)
        self.labelResolution.setAlignment(QtCore.Qt.AlignCenter)
        self.labelResolution.setObjectName("labelResolution")
        self.textMin1 = QtWidgets.QTextEdit(self.tabActions)
        self.textMin1.setGeometry(QtCore.QRect(255, 267, 51, 30))
        self.textMin1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(12)
        self.textMin1.setFont(font)
        self.textMin1.setObjectName("textMin1")
        self.labelMin1 = QtWidgets.QLabel(self.tabActions)
        self.labelMin1.setGeometry(QtCore.QRect(215, 270, 41, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMin1.sizePolicy().hasHeightForWidth())
        self.labelMin1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        self.labelMin1.setFont(font)
        self.labelMin1.setTextFormat(QtCore.Qt.PlainText)
        self.labelMin1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMin1.setObjectName("labelMin1")
        self.labelMax1 = QtWidgets.QLabel(self.tabActions)
        self.labelMax1.setGeometry(QtCore.QRect(305, 270, 41, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMax1.sizePolicy().hasHeightForWidth())
        self.labelMax1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        self.labelMax1.setFont(font)
        self.labelMax1.setTextFormat(QtCore.Qt.PlainText)
        self.labelMax1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMax1.setObjectName("labelMax1")
        self.textMax1 = QtWidgets.QTextEdit(self.tabActions)
        self.textMax1.setGeometry(QtCore.QRect(345, 267, 51, 30))
        self.textMax1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(12)
        self.textMax1.setFont(font)
        self.textMax1.setObjectName("textMax1")
        self.comboBoxValues1 = QtWidgets.QComboBox(self.tabActions)
        self.comboBoxValues1.setGeometry(QtCore.QRect(220, 190, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        self.comboBoxValues1.setFont(font)
        self.comboBoxValues1.setObjectName("comboBoxValues1")
        self.comboBoxValues1.addItem("")
        self.comboBoxValues1.addItem("")
        self.labelValues1 = QtWidgets.QLabel(self.tabActions)
        self.labelValues1.setGeometry(QtCore.QRect(330, 190, 61, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelValues1.sizePolicy().hasHeightForWidth())
        self.labelValues1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        self.labelValues1.setFont(font)
        self.labelValues1.setTextFormat(QtCore.Qt.PlainText)
        self.labelValues1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelValues1.setObjectName("labelValues1")
        self.comboBoxScale1 = QtWidgets.QComboBox(self.tabActions)
        self.comboBoxScale1.setGeometry(QtCore.QRect(220, 240, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        self.comboBoxScale1.setFont(font)
        self.comboBoxScale1.setObjectName("comboBoxScale1")
        self.comboBoxScale1.addItem("")
        self.comboBoxScale1.addItem("")
        self.labelScale1 = QtWidgets.QLabel(self.tabActions)
        self.labelScale1.setGeometry(QtCore.QRect(325, 240, 61, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelScale1.sizePolicy().hasHeightForWidth())
        self.labelScale1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        self.labelScale1.setFont(font)
        self.labelScale1.setTextFormat(QtCore.Qt.PlainText)
        self.labelScale1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelScale1.setObjectName("labelScale1")
        self.labelPlot = QtWidgets.QLabel(self.tabActions)
        self.labelPlot.setGeometry(QtCore.QRect(290, 310, 51, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPlot.sizePolicy().hasHeightForWidth())
        self.labelPlot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        self.labelPlot.setFont(font)
        self.labelPlot.setTextFormat(QtCore.Qt.PlainText)
        self.labelPlot.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPlot.setObjectName("labelPlot")
        self.comboBoxPlot1 = QtWidgets.QComboBox(self.tabActions)
        self.comboBoxPlot1.setGeometry(QtCore.QRect(220, 310, 75, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        self.comboBoxPlot1.setFont(font)
        self.comboBoxPlot1.setObjectName("comboBoxPlot1")
        self.comboBoxPlot1.addItem("")
        self.comboBoxPlot1.addItem("")
        self.comboBoxValues2 = QtWidgets.QComboBox(self.tabActions)
        self.comboBoxValues2.setGeometry(QtCore.QRect(480, 190, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        self.comboBoxValues2.setFont(font)
        self.comboBoxValues2.setObjectName("comboBoxValues2")
        self.comboBoxValues2.addItem("")
        self.comboBoxValues2.addItem("")
        self.labelMin2 = QtWidgets.QLabel(self.tabActions)
        self.labelMin2.setGeometry(QtCore.QRect(475, 270, 41, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMin2.sizePolicy().hasHeightForWidth())
        self.labelMin2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        self.labelMin2.setFont(font)
        self.labelMin2.setTextFormat(QtCore.Qt.PlainText)
        self.labelMin2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMin2.setObjectName("labelMin2")
        self.comboBoxChannel2 = QtWidgets.QComboBox(self.tabActions)
        self.comboBoxChannel2.setGeometry(QtCore.QRect(480, 155, 211, 31))
        self.comboBoxChannel2.setObjectName("comboBoxChannel2")
        self.labelScale2 = QtWidgets.QLabel(self.tabActions)
        self.labelScale2.setGeometry(QtCore.QRect(585, 240, 61, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelScale2.sizePolicy().hasHeightForWidth())
        self.labelScale2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        self.labelScale2.setFont(font)
        self.labelScale2.setTextFormat(QtCore.Qt.PlainText)
        self.labelScale2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelScale2.setObjectName("labelScale2")
        self.textMin2 = QtWidgets.QTextEdit(self.tabActions)
        self.textMin2.setGeometry(QtCore.QRect(515, 265, 51, 30))
        self.textMin2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(12)
        self.textMin2.setFont(font)
        self.textMin2.setObjectName("textMin2")
        self.labelValues2 = QtWidgets.QLabel(self.tabActions)
        self.labelValues2.setGeometry(QtCore.QRect(590, 190, 61, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelValues2.sizePolicy().hasHeightForWidth())
        self.labelValues2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        self.labelValues2.setFont(font)
        self.labelValues2.setTextFormat(QtCore.Qt.PlainText)
        self.labelValues2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelValues2.setObjectName("labelValues2")
        self.labelMax2 = QtWidgets.QLabel(self.tabActions)
        self.labelMax2.setGeometry(QtCore.QRect(568, 270, 41, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMax2.sizePolicy().hasHeightForWidth())
        self.labelMax2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        self.labelMax2.setFont(font)
        self.labelMax2.setTextFormat(QtCore.Qt.PlainText)
        self.labelMax2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMax2.setObjectName("labelMax2")
        self.comboBoxScale2 = QtWidgets.QComboBox(self.tabActions)
        self.comboBoxScale2.setGeometry(QtCore.QRect(480, 240, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        self.comboBoxScale2.setFont(font)
        self.comboBoxScale2.setObjectName("comboBoxScale2")
        self.comboBoxScale2.addItem("")
        self.comboBoxScale2.addItem("")
        self.textMax2 = QtWidgets.QTextEdit(self.tabActions)
        self.textMax2.setGeometry(QtCore.QRect(610, 265, 51, 30))
        self.textMax2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(12)
        self.textMax2.setFont(font)
        self.textMax2.setObjectName("textMax2")
        self.radioButtonCreatingTHeeFiles = QtWidgets.QRadioButton(self.tabActions)
        self.radioButtonCreatingTHeeFiles.setGeometry(QtCore.QRect(180, 20, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(14)
        self.radioButtonCreatingTHeeFiles.setFont(font)
        self.radioButtonCreatingTHeeFiles.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.radioButtonCreatingTHeeFiles.setChecked(False)
        self.radioButtonCreatingTHeeFiles.setObjectName("radioButtonCreatingTHeeFiles")
        self.buttonGroup_6.addButton(self.radioButtonCreatingTHeeFiles)
        self.labelPlotExportChannels = QtWidgets.QLabel(self.tabActions)
        self.labelPlotExportChannels.setGeometry(QtCore.QRect(10, 160, 191, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPlotExportChannels.sizePolicy().hasHeightForWidth())
        self.labelPlotExportChannels.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        self.labelPlotExportChannels.setFont(font)
        self.labelPlotExportChannels.setTextFormat(QtCore.Qt.PlainText)
        self.labelPlotExportChannels.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPlotExportChannels.setObjectName("labelPlotExportChannels")
        self.labelPlottingParameters = QtWidgets.QLabel(self.tabActions)
        self.labelPlottingParameters.setGeometry(QtCore.QRect(10, 240, 191, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPlottingParameters.sizePolicy().hasHeightForWidth())
        self.labelPlottingParameters.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        self.labelPlottingParameters.setFont(font)
        self.labelPlottingParameters.setTextFormat(QtCore.Qt.PlainText)
        self.labelPlottingParameters.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPlottingParameters.setObjectName("labelPlottingParameters")
        self.labelAnd = QtWidgets.QLabel(self.tabActions)
        self.labelAnd.setGeometry(QtCore.QRect(425, 155, 61, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelAnd.sizePolicy().hasHeightForWidth())
        self.labelAnd.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        self.labelAnd.setFont(font)
        self.labelAnd.setTextFormat(QtCore.Qt.PlainText)
        self.labelAnd.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAnd.setObjectName("labelAnd")
        self.radioButtonCreatingCompressedFiles = QtWidgets.QRadioButton(self.tabActions)
        self.radioButtonCreatingCompressedFiles.setGeometry(QtCore.QRect(10, 50, 331, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(14)
        self.radioButtonCreatingCompressedFiles.setFont(font)
        self.radioButtonCreatingCompressedFiles.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.radioButtonCreatingCompressedFiles.setChecked(False)
        self.radioButtonCreatingCompressedFiles.setObjectName("radioButtonCreatingCompressedFiles")
        self.buttonGroup_6.addButton(self.radioButtonCreatingCompressedFiles)
        self.labelAdditionalSettings = QtWidgets.QLabel(self.tabActions)
        self.labelAdditionalSettings.setGeometry(QtCore.QRect(10, 100, 541, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelAdditionalSettings.sizePolicy().hasHeightForWidth())
        self.labelAdditionalSettings.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        self.labelAdditionalSettings.setFont(font)
        self.labelAdditionalSettings.setTextFormat(QtCore.Qt.PlainText)
        self.labelAdditionalSettings.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAdditionalSettings.setObjectName("labelAdditionalSettings")
        self.tabWidget.addTab(self.tabActions, "")
        self.tabMessages = QtWidgets.QWidget()
        self.tabMessages.setObjectName("tabMessages")
        self.tableMessages = QtWidgets.QTableWidget(self.tabMessages)
        self.tableMessages.setGeometry(QtCore.QRect(10, 10, 891, 831))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableMessages.sizePolicy().hasHeightForWidth())
        self.tableMessages.setSizePolicy(sizePolicy)
        self.tableMessages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableMessages.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableMessages.setLineWidth(1)
        self.tableMessages.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableMessages.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableMessages.setObjectName("tableMessages")
        self.tableMessages.setColumnCount(2)
        self.tableMessages.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableMessages.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMessages.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMessages.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMessages.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMessages.setItem(0, 1, item)
        self.tabWidget.addTab(self.tabMessages, "")
        self.pushButtonPause = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonPause.setGeometry(QtCore.QRect(770, 50, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonPause.setFont(font)
        self.pushButtonPause.setCheckable(True)
        self.pushButtonPause.setChecked(True)
        self.pushButtonPause.setFlat(False)
        self.pushButtonPause.setObjectName("pushButtonPause")
        self.buttonGroup_5.addButton(self.pushButtonPause)
        self.labelAlert = QtWidgets.QLabel(self.centralWidget)
        self.labelAlert.setEnabled(True)
        self.labelAlert.setGeometry(QtCore.QRect(30, 77, 451, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelAlert.sizePolicy().hasHeightForWidth())
        self.labelAlert.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(17)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.labelAlert.setFont(font)
        self.labelAlert.setTextFormat(QtCore.Qt.PlainText)
        self.labelAlert.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAlert.setObjectName("labelAlert")
        self.pushButtonClearAlert = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonClearAlert.setEnabled(False)
        self.pushButtonClearAlert.setGeometry(QtCore.QRect(770, 90, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonClearAlert.setFont(font)
        self.pushButtonClearAlert.setCheckable(True)
        self.pushButtonClearAlert.setAutoDefault(False)
        self.pushButtonClearAlert.setFlat(False)
        self.pushButtonClearAlert.setObjectName("pushButtonClearAlert")
        PyEnvDAQ.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(PyEnvDAQ)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 957, 21))
        self.menuBar.setObjectName("menuBar")
        PyEnvDAQ.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(PyEnvDAQ)
        self.mainToolBar.setObjectName("mainToolBar")
        PyEnvDAQ.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(PyEnvDAQ)
        self.statusBar.setObjectName("statusBar")
        PyEnvDAQ.setStatusBar(self.statusBar)

        self.retranslateUi(PyEnvDAQ)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PyEnvDAQ)

    def retranslateUi(self, PyEnvDAQ):
        _translate = QtCore.QCoreApplication.translate
        PyEnvDAQ.setWindowTitle(_translate("PyEnvDAQ", "MainWindow"))
        self.pushButtonStart.setText(_translate("PyEnvDAQ", "start"))
        self.labelProgramName.setText(_translate("PyEnvDAQ", "PyEnvDAQ"))
        self.labelDataWillBeSavedInto.setText(_translate("PyEnvDAQ", "data will be saved into: tritium:\\PyEnvDAQ\\data and tritium:\\PyEnvDAQ\\THeeFiles."))
        item = self.tableChannels.verticalHeaderItem(0)
        item.setText(_translate("PyEnvDAQ", "1"))
        item = self.tableChannels.horizontalHeaderItem(0)
        item.setText(_translate("PyEnvDAQ", "name"))
        item = self.tableChannels.horizontalHeaderItem(1)
        item.setText(_translate("PyEnvDAQ", "unit"))
        item = self.tableChannels.horizontalHeaderItem(2)
        item.setText(_translate("PyEnvDAQ", "factor"))
        item = self.tableChannels.horizontalHeaderItem(3)
        item.setText(_translate("PyEnvDAQ", "offset"))
        item = self.tableChannels.horizontalHeaderItem(4)
        item.setText(_translate("PyEnvDAQ", "raw range (V)"))
        item = self.tableChannels.horizontalHeaderItem(5)
        item.setText(_translate("PyEnvDAQ", "raw value (V)"))
        item = self.tableChannels.horizontalHeaderItem(6)
        item.setText(_translate("PyEnvDAQ", "calibrated value"))
        item = self.tableChannels.horizontalHeaderItem(7)
        item.setText(_translate("PyEnvDAQ", "safe range"))
        item = self.tableChannels.horizontalHeaderItem(8)
        item.setText(_translate("PyEnvDAQ", "status"))
        __sortingEnabled = self.tableChannels.isSortingEnabled()
        self.tableChannels.setSortingEnabled(False)
        item = self.tableChannels.item(0, 0)
        item.setText(_translate("PyEnvDAQ", "happiness"))
        item = self.tableChannels.item(0, 1)
        item.setText(_translate("PyEnvDAQ", "1/abs(expectations-reality)"))
        item = self.tableChannels.item(0, 2)
        item.setText(_translate("PyEnvDAQ", "123"))
        item = self.tableChannels.item(0, 3)
        item.setText(_translate("PyEnvDAQ", "456"))
        item = self.tableChannels.item(0, 4)
        item.setText(_translate("PyEnvDAQ", "[-3V,6V]"))
        item = self.tableChannels.item(0, 5)
        item.setText(_translate("PyEnvDAQ", "4"))
        item = self.tableChannels.item(0, 6)
        item.setText(_translate("PyEnvDAQ", "1.23e-4"))
        item = self.tableChannels.item(0, 7)
        item.setText(_translate("PyEnvDAQ", "[-5,5]"))
        item = self.tableChannels.item(0, 8)
        item.setText(_translate("PyEnvDAQ", "ok"))
        self.tableChannels.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabChannels), _translate("PyEnvDAQ", "Channels"))
        self.comboBoxTimeUnit.setItemText(0, _translate("PyEnvDAQ", "seconds"))
        self.comboBoxTimeUnit.setItemText(1, _translate("PyEnvDAQ", "minutes"))
        self.comboBoxTimeUnit.setItemText(2, _translate("PyEnvDAQ", "hours"))
        self.comboBoxTimeUnit.setItemText(3, _translate("PyEnvDAQ", "days"))
        self.comboBoxTimeUnit.setItemText(4, _translate("PyEnvDAQ", "weeks"))
        self.comboBoxTimeUnit.setItemText(5, _translate("PyEnvDAQ", "months"))
        self.comboBoxTimeDuration.setItemText(0, _translate("PyEnvDAQ", "1"))
        self.comboBoxTimeDuration.setItemText(1, _translate("PyEnvDAQ", "2"))
        self.comboBoxTimeDuration.setItemText(2, _translate("PyEnvDAQ", "4"))
        self.comboBoxTimeDuration.setItemText(3, _translate("PyEnvDAQ", "8"))
        self.comboBoxTimeDuration.setItemText(4, _translate("PyEnvDAQ", "16"))
        self.comboBoxTimeDuration.setItemText(5, _translate("PyEnvDAQ", "32"))
        self.pushButtonExecute.setText(_translate("PyEnvDAQ", "Execute"))
        self.checkBoxAutoUpdate.setText(_translate("PyEnvDAQ", "auto update"))
        self.radioButtonTimePreset.setText(_translate("PyEnvDAQ", "the last"))
        self.radioButtonTimeSpecific.setText(_translate("PyEnvDAQ", "from"))
        self.radioButtonPlot.setText(_translate("PyEnvDAQ", "plot"))
        self.radioButtonExport.setText(_translate("PyEnvDAQ", "export"))
        self.textEditStartDate.setHtml(_translate("PyEnvDAQ", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri Light\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri\'; font-size:12pt;\">2016/02/01 15:14:13</span></p></body></html>"))
        self.textEditEndDate.setHtml(_translate("PyEnvDAQ", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri Light\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri\'; font-size:12pt;\">2016/02/03 16:15:18</span></p></body></html>"))
        self.labelTo.setText(_translate("PyEnvDAQ", "to"))
        self.comboBoxResolution.setCurrentText(_translate("PyEnvDAQ", "1s"))
        self.comboBoxResolution.setItemText(0, _translate("PyEnvDAQ", "1s"))
        self.comboBoxResolution.setItemText(1, _translate("PyEnvDAQ", "5s"))
        self.comboBoxResolution.setItemText(2, _translate("PyEnvDAQ", "15s"))
        self.comboBoxResolution.setItemText(3, _translate("PyEnvDAQ", "1min"))
        self.comboBoxResolution.setItemText(4, _translate("PyEnvDAQ", "30min"))
        self.labelResolution.setText(_translate("PyEnvDAQ", "resolution"))
        self.textMin1.setHtml(_translate("PyEnvDAQ", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri Light\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-1.23</p></body></html>"))
        self.labelMin1.setText(_translate("PyEnvDAQ", "min"))
        self.labelMax1.setText(_translate("PyEnvDAQ", "max"))
        self.textMax1.setHtml(_translate("PyEnvDAQ", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri Light\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-1.23</p></body></html>"))
        self.comboBoxValues1.setCurrentText(_translate("PyEnvDAQ", "raw"))
        self.comboBoxValues1.setItemText(0, _translate("PyEnvDAQ", "raw"))
        self.comboBoxValues1.setItemText(1, _translate("PyEnvDAQ", "calibrated"))
        self.labelValues1.setText(_translate("PyEnvDAQ", "values"))
        self.comboBoxScale1.setCurrentText(_translate("PyEnvDAQ", "manual"))
        self.comboBoxScale1.setItemText(0, _translate("PyEnvDAQ", "manual"))
        self.comboBoxScale1.setItemText(1, _translate("PyEnvDAQ", "automatic"))
        self.labelScale1.setText(_translate("PyEnvDAQ", "scale"))
        self.labelPlot.setText(_translate("PyEnvDAQ", "plot"))
        self.comboBoxPlot1.setCurrentText(_translate("PyEnvDAQ", "linear"))
        self.comboBoxPlot1.setItemText(0, _translate("PyEnvDAQ", "linear"))
        self.comboBoxPlot1.setItemText(1, _translate("PyEnvDAQ", "log"))
        self.comboBoxValues2.setCurrentText(_translate("PyEnvDAQ", "raw"))
        self.comboBoxValues2.setItemText(0, _translate("PyEnvDAQ", "raw"))
        self.comboBoxValues2.setItemText(1, _translate("PyEnvDAQ", "calibrated"))
        self.labelMin2.setText(_translate("PyEnvDAQ", "min"))
        self.labelScale2.setText(_translate("PyEnvDAQ", "scale"))
        self.textMin2.setHtml(_translate("PyEnvDAQ", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri Light\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-1.23</p></body></html>"))
        self.labelValues2.setText(_translate("PyEnvDAQ", "values"))
        self.labelMax2.setText(_translate("PyEnvDAQ", "max"))
        self.comboBoxScale2.setCurrentText(_translate("PyEnvDAQ", "manual"))
        self.comboBoxScale2.setItemText(0, _translate("PyEnvDAQ", "manual"))
        self.comboBoxScale2.setItemText(1, _translate("PyEnvDAQ", "automatic"))
        self.textMax2.setHtml(_translate("PyEnvDAQ", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri Light\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-1.23</p></body></html>"))
        self.radioButtonCreatingTHeeFiles.setText(_translate("PyEnvDAQ", "create THee Files"))
        self.labelPlotExportChannels.setText(_translate("PyEnvDAQ", "plot/export channels"))
        self.labelPlottingParameters.setText(_translate("PyEnvDAQ", "plotting parameters:"))
        self.labelAnd.setText(_translate("PyEnvDAQ", "and"))
        self.radioButtonCreatingCompressedFiles.setText(_translate("PyEnvDAQ", "create compressed pyenv and THee files"))
        self.labelAdditionalSettings.setText(_translate("PyEnvDAQ", "Additional Settings: (Only relevant when plotting or exporting)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabActions), _translate("PyEnvDAQ", "Actions"))
        item = self.tableMessages.verticalHeaderItem(0)
        item.setText(_translate("PyEnvDAQ", "1"))
        item = self.tableMessages.horizontalHeaderItem(0)
        item.setText(_translate("PyEnvDAQ", "time"))
        item = self.tableMessages.horizontalHeaderItem(1)
        item.setText(_translate("PyEnvDAQ", "message"))
        __sortingEnabled = self.tableMessages.isSortingEnabled()
        self.tableMessages.setSortingEnabled(False)
        item = self.tableMessages.item(0, 0)
        item.setText(_translate("PyEnvDAQ", "21-11-16 12:35"))
        item = self.tableMessages.item(0, 1)
        item.setText(_translate("PyEnvDAQ", "reservoir pressure too high. (value at time of message: 500bar)"))
        self.tableMessages.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMessages), _translate("PyEnvDAQ", "Messages"))
        self.pushButtonPause.setText(_translate("PyEnvDAQ", "pause"))
        self.labelAlert.setText(_translate("PyEnvDAQ", "Problem Detected. Check the Messages tab."))
        self.pushButtonClearAlert.setText(_translate("PyEnvDAQ", "Clear Alert"))

